### ISSUE TITLE
Why do you use setf and set ft on the filetype detection script?

### ISSUE THREAD

**Issue by spidey** [martinda/Jenkinsfile-vim-syntax#10]
This is not actually an issue, just a doubt which I couldn't find where to talk about. Why do you use setf and set ft on the filetype detection script? Was this a deliberate choice? Could you expand on the reason?

I'm learning VimL, read the Learn Vimscript the Hard Way book but to me it just seemed like a random choice that didn't deserve an extra commit to be fixed.

The only thought on it is that maybe the `set ft=` files are detected as plaintext or some other format previously and need to be overridden.

**Comment by martinda** [comment]
@spidey Honestly I do not remember. I do not use it much either these days.
